<!-- code phtml qu'on incluera dans master.phtml avec la fonction getFooter() de la classe Init -->

<footer>
	<section class="contacts">
		<article>
			<h3><i class="fa fa-envelope" aria-hidden="true"></i></h3>
			<div>
				<a class="coord" href="mailto:Kenrabari@yahoo.fr"> <i class="couleur">Kenny.Eric@gmail.com</i></a>
			</div>
		</article>
		<article>
			<h3><i class="fa fa-phone" aria-hidden="true"></i></h3>
			<div>
				<a class="coord" href="tel:+33664680168"> <i class="couleur">+33 8 76 54 32 01</i></a>
			</div>
		</article>
		<article>
			<h3><i class="fa fa-paper-plane" aria-hidden="true"></i></h3>
			<a class="coord" href=""> <i class="couleur">Paris, FRANCE</i></a>
		</article>
	</section>
	<p>
		<small>© Copyright 2018 Kenny-Eric Rabarisoanaivo.</small>
	</p>							
</footer>