<!-- code phtml représentant le contenu d'accueil que l'on incluera dans master.phtml avec la fonction getTemplate_name() de la classe Init -->

<section class="competences">

	<h2 id="comp">Mes compétences</h2>

	<article>
		<h3><strong>Web</strong></h3>  
			<ul class="web">
			<li class="majuscule">html5</li>
			<li class="majuscule">css3</li>
			<li class="majuscule">php</li>
			<li>JavaScript</li>
			<li>MySQL</li>
		</ul>
	</article><article>  
		<h3><strong>Langages</strong></h3>					
		<ul>
			<li>Java / JEE</li>
			<li>C++</li>
			<li>C</li>
			<li>OCaml</li>
			<li>Python</li>
			<li>Shell</li>
			<li class="majuscule">xml</li>						
		</ul>
	</article><article> 				
		<h3><strong>Editeurs/IDE</strong></h3>					
		<ul>
			<li>Eclipse</li>
			<li>NetBeans</li>
			<li>Cocoa</li>
			<li>Visual Studio</li>
			<li>Atom</li>
			<li>Sublime Text</li>
			<li>Emacs</li>
		</ul>
	</article><article> 				
		<h3><strong>Systèmes</strong></h3>
		<ul>
			<li>Ubuntu</li>
			<li>Debian</li>
			<li>FreeBSD</li>
			<li>Windows</li>
		</ul>
	</article>
</section>

<section class="realisations">				

	<h2 id="real">Mes projets et réalisations web</h2>

	<article>
		<i class="fa fa-coffee cercle_fa" aria-hidden="true"></i>
		<h3>2017-2018</h3>
		<strong>Développement d'un site web en ligne</strong>

		<ul>
			<li>Intégration de maquettes en HTML5 et CSS3</li>
			<li>Création d'une base de données en MySQL</li>
			<li>Développement client/serveur en PHP et JavaScript</li>							
		</ul>
	</article><article>
		<i class="fa fa-flask cercle_fa" aria-hidden="true"></i>
		<h3>2015-2016</h3>
		<strong>Développement d'un framework afin d'implémenter des jeux de courses</strong>
		<ul>
			<li>Langage utilisé: C++</li>
			<li>Utilisation du motif: Modèle/Vue/Contrôleur (MVC)</li>
			<li>Environnement de travail: Atom</li>							
		</ul>
	</article><article>
		<i class="fa fa-code cercle_fa" aria-hidden="true"></i>
		<h3>2013-2014</h3>
		<strong>Implémentation d'un correcteur d'orthographe</strong>
		<ul>
			<li>Langage utilisé: Python</li>
			<li>Détection des mots mal-orthographiés d'un fichier</li>
			<li>Liste de suggestions pour chaque erreur</li>
			<li>Sauvegarde du texte corrigé dans un nouveau fichier</li>											
		</ul>
	</article>
</section>

<section class="exemples">			

	<h2 id="exem">Quelques exemples de mes réalisations</h2>

	<article>
		<h3>Cup Of Tea:</h3>

		<img src="img/realisation/1.png" alt="maquette1"/>

		<p>Le thé représente une vaste gamme de boissons aromatiques, gustatives ou désaltérantes, obtenues par infusion ou percolation d'eau sur diverses préparations à partir des petites feuilles et des bourgeons de théier, un arbuste à feuilles persistantes originaire d'Asie. Ces diverses boissons aqueuses peuvent être par exemple obtenues à partir de feuilles séchées (thé vert) ou diversement fermentées (thé noir), selon les traditions, les portions liquides sont bues chaudes, tièdes ou froides, en quantités très variables, diluées, faiblement ou fortement concentrées, et parfois additionnées de diverses matières d'origine végétale ou animale.</p>

		<p>Parce que le thé est avant tout une origine, Cup Of Tea parcourt le monde pour vous faire découvrir des récoltes d’exception. De la relation engagée que nous cultivons avec chacun de nos producteurs naît une infinie palette de saveurs et d’émotions.</p>

		<a href="../integration/maquettes/M12_-_Cup_of_Tea/" class="bouton">Voir le site<i class="fa fa-plus-circle" aria-hidden="true"></i></a>
	</article>
	<article> 
		<h3>Mingeek:</h3>

		<img src="img/realisation/2.png" alt="maquette2"/>

		<p>MindGeek continue de faire évoluer la technologie vers le futur en développant les principales solutions de l’industrie pour une livraison plus rapide et plus efficace du contenu chaque seconde à destination de millions de clients à travers le monde. L’entreprise travaille chaque jour à l’amélioration de ses capacités technologiques et à développer une croissance durable fondée sur l’innovation et l’excellence.</p>

		<p>Avec plus de 1000 employés dans le monde entier, MindGeek poursuit son expansion avec l’acquisition et l’octroi de licence pour certaines des marques les plus emblématiques du secteur des médias et du divertissement</p>

		<p>MindGeek est l’une des principales entreprises de technologie de l’information au monde avec des bureaux au Luxembourg, à Nicosie, à Hambourg, à Londres, à Montréal, à Bucarest et à Los Angeles.</p>

		<a href="../integration/maquettes/M11_-_Mindgeek/" class="bouton">Voir le site<i class="fa fa-plus-circle" aria-hidden="true"></i></a>
	</article>
	<article>
		<h3>Wolf Gang:</h3>

		<img src="img/realisation/3.png" alt="maquette3"/>

		<p>L'objectif de Wolf Gang étant la meilleure vitesse et la prise d'angle sur les virages, elles sont généralement dotées de moteurs optimisés pour les montées à hauts régimes, de freins puissants.</p>

		<p>A cylindrée égale, elles sont souvent plus performantes et plus fragiles que les machines des autres catégories et souvent plus légères.</p>

		<p>Parfois dérivées des modèles de compétition, les motos sportives de Wolf Gang pourtant homologuées pour un usage routier (rétroviseurs, normes anti-pollution, feux, clignotants et plaque d'immatriculation) restent d'un intérêt limité au quotidien en milieu urbain ou autoroutier (du fait de la position de conduite, l'amortissement et la manœuvrabilité à l’arrêt).</p>

		<a href="../integration/maquettes/M09_-_Wolf_Gang/" class="bouton">Voir le site<i class="fa fa-plus-circle" aria-hidden="true"></i></a>
	</article>
	<article>
		<h3>Creasoul:</h3>

		<img src="img/realisation/4.png" alt="maquette4"/>

		<p>Creasoul est une société de Branding située à Kannur, Kerala. Notre vision consiste à fournir à nos clients des solutions informatiques de haute qualité à valeur ajoutée en combinant les compétences technologiques, l'expertise en matière de processus d'expertise du domaine et l'engagement envers une relation client à long terme.</p>

		<p>Une synthèse précise sur les avancées les plus récentes de l'informatique et des télécommunications, sur leurs évolutions prévisibles à court et moyen terme, et leur impact sur les entreprises : construire des réseaux services, les sécuriser ; maîtriser les technologies Internet ; mesurer l'impact de la mobilité et du commerce électronique ; intégrer la mobilité dans les méthodes de développement ; mettre en place des applications client-serveur et Cloud ; choisir un processus de développement adapté aux nouvelles technologies.</p>

		<a href="../integration/maquettes/M08_-_Creasoul/" class="bouton">Voir le site<i class="fa fa-plus-circle" aria-hidden="true"></i></a>
	</article>
</section>

<section class="interets">			

	<h2 id="lois">Mes centres d'intérêt</h2>

	<article>  								
		<img src="img/loisir/montage_videos.jpg" alt="loisir1"/>
		<h3><strong>Montages vidéos</strong></h3>
	</article><article>								
		<img src="img/loisir/piano.jpg" alt="loisir2"/>
		<h3><strong>Piano</strong></h3> 
	</article><article>														
		<img src="img/loisir/salsa.jpg" alt="loisir3"/>	
		<h3><strong>Salsa</strong></h3>										
	</article>
</section>

<section class="messages">

	<h2 id="mess" class="zeromsg">Liste des messages</h2>

	<?php if ($page->getFlashBag2()->contientMessages()) : ?>
		<?php foreach ($page->getFlashBag2()->Messages() as $msg) : ?>

			<div class="success pos1"><?= $msg; ?></div>
								
		<?php endforeach; ?>	
	<?php endif ?>

	<h3 id="nb_msg"><?= $fct->pluriel_ou_pas(count($page->getMessages()),"message"); ?>:</h3>

	<?php foreach ($page->getMessages() as $index => $message) : ?>

		<article class="message_content">
			<div class="topline">
				<a href="php/message.php?id=<?= $message['id']; ?>" title="voir le message en détail"><h3 class="souligne"><?= $message['titre']; ?></h3></a>

				<?php if($page->getUserSession()->estConnecte()): ?>
					<div class="buttons">
						<a href="index.php#mess" title="supprimer le message" onClick="return confirmerSupprimerMessage(<?= $message['id']; ?>, <?= $message['id_user']; ?>, <?= $page->getUserSession()->getId(); ?>, <?= $message['nbc']; ?>)">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				<?php endif; ?> 
			</div>

			<p><?= $page->debutparagraphe($message, $fct); ?></p>

			<small class="published">
				<a href="index.php#mess">
					<i class="fa fa-calendar" aria-hidden="true"></i>
					Publié le <?= $fct->formatDateFrance($message['date']); ?>, par <i><?= $message['prenom'] . ' ' . $message['nom']; ?></i>
				</a>
				<a href="php/message.php?id=<?= $message['id']; ?>" title="voir le message en détail" class="souligne nb_rep">
					<i class="fa fa-comment" aria-hidden="true"></i>
					<?= $fct->pluriel_ou_pas($message['nbc'], "réponse"); ?> 
				</a>						
			</small>
		</article>

	<?php endforeach; ?>
																					
</section>

<section class="contact">

	<h2 id="cont">Contactez-moi</h2>

	<?php if($page->getUserSession()->estConnecte()): ?>

		<p class="msg">Si vous avez des questions, n'hésitez pas à poster un message à l'aide du formulaire ci-dessous. Vous pouvez aussi me joindre à l'aide de mes coordoonées ci-dessous.</p>

		<form action="php/add_message.php" method="POST" onSubmit="return confirmerPublier();">	       			
			<input type="text" name="object" id="object" placeholder="Objet du message">	       			
			<textarea name="ecrire" rows="10" placeholder="Publier un message" required></textarea>

			<button type="submit" id="B1">Envoyer</button>
			<button type="reset" id="B2">Annuler</button>
		</form>

	<?php else: ?>

		<p class="msg">Pour publier un message, vous devez être connecté.<br/>(allez dans 'connexion')</p>

	<?php endif; ?> 
</section>



